# 顶部添加：指定使用清华镜像源（名称和步骤2中的一致）
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Netflix-Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Netflix-Clone
   pod 'SDWebImage'
end
